id: fhir.ig.happyhour
canonical: http://example.org
name: HappyHour
title: The Happy Hour FHIR Implementation Guide
description: Laughter may be the best medicine, but Alcohol is a close second.
status: draft 
version: 1.4.2022
fhirVersion: 5.0.0-snapshot1
copyrightYear: 2022+
releaseLabel: ci-build 
publisher:
  name: Audacious Inquiry
  url: www.ainq.com
  email: dpyke@ainq.com

pages:
  index.md:
    title: Happy Hour FHIR Implementation Guide
  implementation.md:
  examples.md:
    title: Examples Overview
    
parameters:
    excludettl: true

menu:
  Home: index.html
  Examples : examples.html
  Implementation : implementation.html
  Artifacts: artifacts.html

contact:
  - name: Dave Pyke
    telecom:
      - system: email 
        value: dpyke@ainq.com
        use: work
